Repository KKumiRoom/KKumiRoom-BE, pull requests merged in 2025-05, with the labels that each got.

#1 merge: 중복 저장 문제 해결
  src/main/java/com/example/kummiRoom_backend/api/entity/Course.java
  src/main/java/com/example/kummiRoom_backend/api/entity/School.java
  src/main/java/com/example/kummiRoom_backend/openApi/OpenApiService.java
  src/main/java/com/example/kummiRoom_backend/openApi/dto/requestDto/NeisTimetableRequestDto.java
Labels: documentation

#6 feat: 시간표 테이블 courseType판별 로직 추가
  src/main/java/com/example/kummiRoom_backend/openApi/OpenApiService.java
Labels: documentation

#5 fix: 사용자 프로필 업데이트에 이미지 추가
  src/main/java/com/example/kummiRoom_backend/api/dto/requestDto/UpdateProfileRequestDto.java
  src/main/java/com/example/kummiRoom_backend/api/dto/responseDto/UserProfileResponseDto.java
  src/main/java/com/example/kummiRoom_backend/api/entity/User.java
  src/main/java/com/example/kummiRoom_backend/api/service/UserService.java
Labels: documentation

#7 feature: 학교 정보 수정
  src/main/java/com/example/kummiRoom_backend/api/controller/UserController.java
  src/main/java/com/example/kummiRoom_backend/api/dto/requestDto/UpdateSchoolInfoRequestDto.java
  src/main/java/com/example/kummiRoom_backend/api/service/UserService.java
Labels: enhancement

#10 feature: 사용자 비밀번호 변경
  src/main/java/com/example/kummiRoom_backend/api/controller/UserController.java
  src/main/java/com/example/kummiRoom_backend/api/dto/requestDto/ChangePasswordRequestDto.java
  src/main/java/com/example/kummiRoom_backend/api/service/UserService.java
Labels: enhancement

#11 feat: 회원 가입시 타임 테이블 자동 생성
  src/main/java/com/example/kummiRoom_backend/api/controller/AuthController.java
  src/main/java/com/example/kummiRoom_backend/api/controller/TimeTableController.java
  src/main/java/com/example/kummiRoom_backend/api/controller/TimeTableEntryController.java
  src/main/java/com/example/kummiRoom_backend/api/service/TimeTableService.java
  src/main/java/com/example/kummiRoom_backend/global/auth/AuthService.java
Labels: enhancement

#16 fix: jwt filter 응답 수정, blacklist 삭제
  src/main/java/com/example/kummiRoom_backend/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/kummiRoom_backend/global/config/security/SecurityConfig.java
Labels: enhancement

#17 fix: security config 수정
  src/main/java/com/example/kummiRoom_backend/global/config/security/SecurityConfig.java
Labels: bug
